language: python
notifications:
  email: false
python:
  - "3.4"
install:
  - pip install pytest-pep8 pytest-cov
  - pip install -r requirements.txt
script:
  - "py.test --pep8 --clearcache --cov gitmostwanted tests/unit"
