# this file is used during the deployment process

version: '3.7'
services:
  gmw_db:
    volumes:
      - /home/github_gitmostwanted/data/mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    networks:
      - gmw_network

  gmw_redis:
    entrypoint: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /home/github_gitmostwanted/data/redis:/data
    labels:
      - "traefik.enable=false"
    networks:
      - gmw_network

  gmw_celery:
    volumes:
      - /home/github_gitmostwanted/data/celery:/data
      - /home/github_gitmostwanted/gitmostwanted:/etc/gitmostwanted
    environment:
      - GMW_APP_ENV=production
      - GMW_APP_SETTINGS=/etc/gitmostwanted/instance.cfg
    labels:
      - "traefik.enable=false"
    networks:
      - gmw_network

  gmw_web:
    volumes:
      - /home/github_gitmostwanted/gitmostwanted:/etc/gitmostwanted
    environment:
      - GMW_APP_ENV=production
      - GMW_APP_SETTINGS=/etc/gitmostwanted/instance.cfg
    networks:
      - gmw_network
    labels:
      - "traefik.http.routers.gmw_web.rule=Host(`gitmostwanted.com`)"

networks:
  gmw_network:
    external:
      name: traefik_default
