gitmostwanted:
  build: .
  command: python web.py
  ports:
    - "5000:5000"
  volumes:
    - ./:/opt
  environment:
    - GMW_APP_SETTINGS=/opt/instance.cfg
  links:
    - db

db:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
