version: '3.7'
services:
  db:
    volumes:
      - /home/github_gitmostwanted/data/mysql:/var/lib/mysql

  redis:
    entrypoint: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /home/github_gitmostwanted/data/redis:/data
