# this file is used during the deployment process

version: '3.7'
services:
  db:
    volumes:
      - /home/github_gitmostwanted/data/mysql:/var/lib/mysql

  redis:
    entrypoint: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /home/github_gitmostwanted/data/redis:/data

  celery:
    volumes:
      - /home/github_gitmostwanted/data/celery:/data

  web:
    environment:
      - GMW_APP_ENV=production
      - GMW_APP_SETTINGS=/home/github_gitmostwanted/gitmostwanted/instance.cfg

