web:
  build: .
  user: gitmostwanted
  entrypoint: ["/opt/entrypoint.sh"]
  ports:
    - "5000:5000"
  volumes:
    - ./gitmostwanted:/opt/gitmostwanted
    - .:/opt
  environment:
    - GMW_APP_SETTINGS=/opt/instance.cfg
  links:
    - dbGmw

celery:
  build: .
  user: gitmostwanted
  command: celery -A gitmostwanted.app.celery worker -B -s /tmp/celerybeat-schedule.dat --autoreload --loglevel=DEBUG
  environment:
      - GMW_APP_SETTINGS=/opt/instance.cfg
  volumes_from:
    - web
  links:
    - dbGmw
    - redis

dbGmw:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=gitmostwanted
    - MYSQL_USER=gitmostwanted
    - MYSQL_PASSWORD=gitmostwanted_pwd

redis:
  image: redis:latest
