gitmostwanted:
  build: .
  command: python web.py
  ports:
    - "5000:5000"
  volumes:
    - ./gitmostwanted:/opt/gitmostwanted
  links:
    - db

db:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
