name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: initialize submodules
      run: git submodule update --init --recursive

    - name: artifacts
      run: |
        mkdir /tmp/output
        mv -t /tmp/output alembic.ini requirements.txt Dockerfile gitmostwanted migration scripts \
          docker-compose.yml docker-compose-persistent.yml entrypoint.sh

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: /tmp/output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts

      - name: known_hosts update
        run: echo "${{secrets.KNOWN_HOSTS_ENTRY}}" >> ~/.ssh/known_hosts

      - name: source-code upload
        run: rsync -az --delete-after artifacts/ ${{secrets.SSH_LOGIN}}@88.198.242.237:/home/github_gitmostwanted/artifacts/${GITHUB_SHA::8}

      - uses: geekyeggo/delete-artifact@v1
        with:
          name: artifacts
